# Generated by Django 4.2.3 on 2023-08-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('producto_final', models.CharField(max_length=500)),
                ('objetivo', models.TextField()),
                ('producto_parcial', models.TextField()),
                ('presentacion', models.TextField()),
                ('integracion', models.TextField()),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
    ]
