# Generated by Django 4.2.4 on 2023-08-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0003_productoacademico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contenido",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre_contenido", models.CharField(max_length=200)),
                ("numero_contenido", models.IntegerField()),
                ("estado", models.CharField(default="A", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="responsables",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre_responsable", models.CharField(max_length=200)),
                ("cargo_responsable", models.CharField(max_length=200)),
                ("firma_responsable", models.CharField(max_length=200)),
                ("estado", models.CharField(default="A", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="unidades",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre_unidad", models.CharField(max_length=200)),
                ("objetivo_unidad", models.CharField(max_length=650)),
                ("numero_unidad", models.IntegerField()),
                ("horas_docencia", models.IntegerField()),
                ("horas_practica", models.IntegerField()),
                ("estado", models.CharField(default="A", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="versiontest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre_version", models.CharField(max_length=200)),
                ("fecha_creacion", models.DateField()),
                ("estado", models.CharField(default="A", max_length=3)),
            ],
        ),
    ]
