# Generated by Django 4.2.3 on 2023-08-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_contenido_responsables_unidades_versiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='aportes_perfil_egreso',
            field=models.CharField(default='default value', max_length=600),
            preserve_default=False,
        ),
    ]
