# Generated by Django 4.2.4 on 2023-08-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_asignatura_aportes_perfil_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='A', max_length=3)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores_asignatura', to='processos.asignatura')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores_contenido', to='processos.contenido')),
                ('producto_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores_producto_academico', to='processos.productoacademico')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores_referencia', to='processos.referencias')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores_responsable', to='processos.responsables')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores_unidad', to='processos.unidades')),
            ],
        ),
    ]
